### ISSUE TITLE
Deploymen fails - Error 401 status code on windows

### ISSUE THREAD

**Issue by kunle-e** [skhatri/grunt-nexus-deployer#31] opened 2016-11-02 21:05 UTC
grunt-nexus-deployer@0.1.0 produces error code 401 when attempting to deploy on
windows 10, node v4.2.4

I downgraded to grunt-nexus-deployer@0.0.7 and it works.

**Comment by patrickkostjens** [comment] 2017-02-01 08:46
I ran into the same problem. Turns out to be caused by the fact that single quotes don't work with credentials in curl for windows. It was fixed in this commit:
https://github.com/skhatri/grunt-nexus-deployer/commit/4c126ca149a5fd7eb7cf5f41026385ed9f1b0e73

It was released in version 0.2.1, so if you upgrade to that version or a later one, your problem should be solved.

I think this issue can then be closed, but I'm not the maintainer so I can't do it. I just thought I'd share the solution in case you hadn't seen it yet.

**Comment by skhatri** [comment] 2017-02-14 11:04
Thanks @patrickkostjens

**Closed** 2017-02-14 11:04 UTC
